### ISSUE TITLE
Itheum Enterprise UI

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#1076]

**Comment by fuzzyduke** [comment]
Few notes discussed in collaboration with @Enciusan as well.

1. Only 1 data NFT from a collection can currently be minted.
2. Time between mints needs to show if its request for in minutes or so.
3. What is tax token amount? Please illustrate with example.
4. Please associate tooltips to fields for better understanding of what the user is inputting
5. Success was seen on a transaction however it failed because of incorrect token ticker, that currently has limitations. https://devnet-explorer.multiversx.com/transactions/6f256efd494f20fb0ac17b950f27f0b1f4b410832d2c11d157083df2e4885fe0#ac55e4ca52f7f044737a326c4346925b4847ca16d9f209ff1a4a74426bd39b52
6. While minting it is seen that the roles have to be set and transaction has to be signed. This has to be more intuitive. What roles are being set to the address in question.
7. Currently Preivew URL doesnt have any error message. Show we keep preview as mandatory?
8. Update other settings does not show current addresses that allow this.
9. Token title doesnt accept special characters like "#" this generally is required to show the number of the nft in the series.
10. When clicking on the xoxno data nft and going to the detail page we are not able to set the sell offer price. Only in the listing page we can select the row and set a sales price.
11. Claims url is required. Also it is required to show various tokens that can be claimed. Need the interface to better detail this element.

cc: @Enciusan @damienen

**Comment by damienen** [comment]
The only thing that needs to be fixed in this milestone is vi and the fact that this control does not appear and is auto called:
![Image](https://github.com/Itheum/data-dex/assets/44813558/24dfbb5f-d1f4-464e-b79f-3ddf3728f2df)

**Comment by damienen** [comment]
Solved. Closing.
