### ISSUE TITLE
Error seen when performing early withdrawal in specific scenario

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1289]
Bond amount: 10 ITHEUM

Penalty was set to 5%
Maximum Slash: 50%
Early withdrawal:35%

After penalty of 5% was applied, 9.5 ITHEUM remained 
After Slash of 50% was applied, 4.5 remained
Early withdrawal of 35% threw an error below, when we still have 45% remaining. It should deduct and return 10% to the user.

https://devnet-explorer.multiversx.com/transactions/e8a346efc1cb30d5791c9dd390829631937e886b5da03890b23061522fd33d45

![image](https://github.com/Itheum/data-dex/assets/121969933/44c187b7-7e36-4089-a066-05a39da31316)
![image](https://github.com/Itheum/data-dex/assets/121969933/fc5029ed-fe90-4fee-bec1-26aab8b994b1)

**Comment by bucurdavid** [comment]
This fall more into this case:
![Image](https://github.com/Itheum/data-dex/assets/46384319/dade0457-7a24-4d96-a92d-62db885abfe9)

| Bond | Value | Compensation | Value |
| ------|-----| --------| -----|
| bond amount | 10 ITHEUM | accumulated amount | 0 ITHEUM 
| remaining  amount  | 10 ITHEUM | 

After 5% and 50%
| Bond | Value | Compensation | Value |
| ------|-----| --------| -----|
| bond amount | 10 ITHEUM | accumulated amount | 5.5 ITHEUM 
| remaining  amount  | 4.5 ITHEUM | 

If user tries to withdraw before unbond period(timestamp) 35% is added 

After another 35% 
| Bond | Value | Compensation | Value |
| ------|-----| --------| -----|
| bond amount | 10 ITHEUM | accumulated amount | 5.5 + 3.5(9)  ITHEUM 
| remaining  amount  | 4.5 - 3.5 (1.5) ITHEUM | 


But there is another check here: remaining amount (4.5) - penalty (3.5) > accumulated_amount (5.5), because this check is `false` the value it's "forfeit".

The user should be able to withdraw 1.5 after the unbond period has passed.

CC: @damienen  @newbreedofgeek

**Comment by damienen** [comment]
Solved. Closing
