### ISSUE TITLE
Elrond - Fix error "ER1" for new wallets with nonce 0

### ISSUE THREAD

**Issue by bucurdavid** [Itheum/data-dex#137]
I know that on the mainnet there won't be many users who will have nonce 0, but I think we should handle this exception.

If a new user with nonce 0 uses data dex it will show the error "ER1: Could not get your token information from the Elrond blockchain ".
![image](https://user-images.githubusercontent.com/46384319/204107937-b3369038-791d-4e00-b2e1-7712d7482dd8.png)

The response from the **devnet-api** and **api** for the user balance is:
`{"statusCode":500,"message":"Internal server error"}`

**Comment by newbreedofgeek** [comment]
If this is happening because it a "brand new wallet" (i.e wallet nonce is 0) - then maybe we can handle this error by should ITHEUM tokens as 0 and not throwing the error. This is the same as if a user has zero ITHEUM, the API actually throws a 404 - but we handle it and show 0 ITHEUM tokens.

**Comment by damienen** [comment]
Internal (Nath )

Description Login with a new wallet ( no XEGLD in the wallet will provide an error- check pic attached )

Steps to reproduce:
Step1) Create a new wallet
Step2) Use the newly created wallet to connect to the Data DEX
Step3) Receive the error

Expected Behavior: I expected this connection to be smooth, with no errors because the wallet was empty.


![image](https://user-images.githubusercontent.com/118804443/215523482-0706a0ae-b6f9-412b-8238-bd305d6c6d7e.png)

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1408854046_
