### ISSUE TITLE
Buying a FREE Data NFT from the marketplace does not work

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#214]
Using Ledger, but should also be same for other wallets. Used, Brave Browser but will be same with others.

- When I tried to but a FREE Data NFT, the browser threw a JS error and the screen went black.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/743169/217119976-d214447e-6065-4aed-89a1-39d11b447b0c.png">

- This was FREE Data NFT I tried to buy
<img width="263" alt="image" src="https://user-images.githubusercontent.com/743169/217120104-52502570-2452-48f2-8bc9-95003e6ddd5f.png">

**Comment by icegriffinguru** [comment]
![image](https://user-images.githubusercontent.com/97042732/217182441-2f76f744-c2a9-4252-9364-db99a8e9d033.png)

I remember.
This issue is caused by zero token transfer.
Zero token transfer causes a wallet panics.
I argued with Elrond team that we need zero token transfer but they did not listen.
I will remove token transfer payload if token amount is zero.

**Comment by icegriffinguru** [comment]
Fixed.
