### ISSUE TITLE
Burn Supply feature on Data NFT permits negative amount in interface.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#225]
**Type**: Bug

**Description**: 
While Burning NFT, a negative amount entry is possible.

**Steps to reproduce**

1. Click on Burn
2. In the textbox add negative number. (Decrease amount toggle)

**Expected Behavior:** 
Negative entries should not be possible.

**Actual Behavior**
1. Entry of negative numbers possible.
2. Error message not conclusive.

![image](https://user-images.githubusercontent.com/121969933/217652349-5da60cf0-37be-4708-ab0b-fa7010a55a7f.png)

**Comment by damienen** [comment]
Expected behavior as long as it gets correct on blur.

But the error message should be better. It shouldn't say it can't be zero if you input -5 for example.

It should say it cannot be under 1 or something. 

Also, the buttons (up and down arrow shouldn't allow the user to go over min and max, again, like it's implemented in the Mint Data NFT Modal)

**Comment by icegriffinguru** [comment]
Fixed

**Comment by fuzzyduke** [comment]
QA verified. Fixed.

Note: Default value is set to max NFTs owned.

![image](https://user-images.githubusercontent.com/121969933/218049208-b94d3a54-359b-4640-97a8-9ffbf61b796f.png)
