### ISSUE TITLE
Data NFT Details: AGE field filter doesn't correctly check value to filter results.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#386]
Description:

1. Placing "AGE" as 2 or 7 returns the same results for output of 27 days which is wrong. Also please consider a greater or less than for age as then it becomes more relevant.

![image](https://user-images.githubusercontent.com/121969933/226477990-1533f1eb-cca6-4283-a513-aad9fcca76bd.png)

**Comment by damienen** [comment]
There's multiple ways to do this and it requires some archtiectural decisions:
1. We can use a new library to implement an age filter with a date RANGE picker the same way it's implemented on the MultiversX mainnet explorer
2. We can use two normal Date Pickers in order to select a min and a max separately'
3. We can leave this be as right now a fuzzy search is implemented and it could be helpful and intuitive to just write "360 days" when you want to search for old transactions even though there's this inconvenient

**Comment by newbreedofgeek** [comment]
this can move to future work

**Comment by damienen** [comment]
You can take inspiration from MX's mainnet explorer

**Comment by bucurdavid** [comment]
Have you any idea of a package that I can use?

**Comment by bucurdavid** [comment]
As I understand in the Filter class code, it takes a value (string or number) and it filters based on that. I think even using a date picker will not work with the current implementation of the Filter class because it will update the value and filter on a specific date picked

**Comment by damienen** [comment]
Good job! Love the implementation
