### ISSUE TITLE
DataNFT marketplace page '0' is not needed

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#432]
This URL:
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market/0

Should be:
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market

We dont need a "page 0". 

So URLs should be:
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market/1
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market/2
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market/3
erc...

**Comment by icegriffinguru** [comment]
Fixed by starting pageNumber as 1, not 0.
because `https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market` this url needs more routing cases and handlers.

**Comment by damienen** [comment]
The existance of page 0 or 1 is not an issue in itself. 

What should be solved in order to close this issue, I think, is:
1. https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/datanfts/marketplace/market should work, too, even if there is no 0, 1, 2, 3, etc. in the end of the URL. If no number is provided, it should default to the first page.
2. If possible, we should not show the /1 or /0 part of the link if they are on the first page of the marketplace.
3. Same as above for "My listed NFTs"

**Comment by icegriffinguru** [comment]
Fixed again
