### ISSUE TITLE
Misc Bugs with Minter Form

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#444]
1. All the input "guidelines" are missing. Here is the old design that's needed

<img width="472" alt="image" src="https://user-images.githubusercontent.com/743169/228831100-c015393f-d208-4299-8a6c-cfe83d707102.png">

2. I was adding removing values for number of copies  and royalties and saw this issue: (select the number, clear it and you will see it)
<img width="648" alt="image" src="https://user-images.githubusercontent.com/743169/228830645-3e673c4a-d18d-4b5a-a599-31b844e65c71.png">
<img width="621" alt="image" src="https://user-images.githubusercontent.com/743169/228831284-9e81beb9-97e8-486b-8e32-26a24044391b.png">

**Comment by damienen** [comment]
This seems to be because of the special character ":", dint catch this at the time. There needs to be a validation message over that field however.

_Originally posted by @fuzzyduke in https://github.com/Itheum/data-dex/issues/447#issuecomment-1491532565_

Check this one, too. Closed so we don't spam with form issues

**Comment by damienen** [comment]
Solved. Closing
