### ISSUE TITLE
Delist NFTs even if you are not the owner/creator ( TX fail ) but UI Bug

### ISSUE THREAD

**Issue by BogdanCostinas** [Itheum/data-dex#505]
**Description**
While waiting for the UI to load on the marketplace, if you quickly swap pages from the Public Marketplace to My listed Data NFTs, there's a bug, you have to option to DELIST, Modify the prices of other Data NFTs, even if you are not the owner/creator of that particular NFT ( Works both ways ) 

**Steps to reproduce**  
Step 1) Quickly swap between Public listed and My listed Data nft's multiple times ( basically spam the webpage with swaps between those two tabs )
Step 2) Go to public marketplace and click on the next page of the marketplace or the last page of the marketplace
Step 3) Before it loads, quickly go to My listed data nft
Step 4) The bug it's there, other NFTs that are not yours appear on that page and you can delist/update price ( even the tx fails )

Additional information: With a bad internet connection, it has the same behaviour

**Expected behavior:**
No matter how bad is the connection, there should not appear NFTs that are not mine in "My listed Data NFTs"

**Comment by damienen** [comment]
As a solution we could block the buttons to switch between marketplace and my listed nfts while it's in a loading state

**Comment by newbreedofgeek** [comment]
@fuzzyduke pls test on demo link found here - https://github.com/Itheum/data-dex/pull/523

**Comment by fuzzyduke** [comment]
Page refresh has to be reviewed.

1. Wallet has 3 tiles on the first row, while Marketplace has 5 tiles on the first row.
2. When switching from Marketplace to Wallet, you see for a brief second 5 tiles instead of 3.
3. Also when switching between them observe how the text of marketplace tiles briefly shows on My data NFT tiles.
4. When moving from wallet to marketplace there are 3 tiles instead of 5, with the text briefly showing of tiles from previous section.

Please check the link below
https://www.loom.com/share/1b63c01933214bc5a63bb4f1f077083d

**Comment by icegriffinguru** [comment]
Fixed, @fuzzyduke

**Comment by fuzzyduke** [comment]
The above has been fixed, with comment.

Observations.
1.  When switching there is no cached loading screens or text from the previous state.

Clarification.
1. The **loading cards** are no longer observer. As the page loads there is a circle loading icon.

@damienen @newbreedofgeek

**Comment by damienen** [comment]
Loading cricle not intended. We should still show skeletons

**Comment by icegriffinguru** [comment]
@fuzzyduke 
a new fix pushed
plz check again

**Comment by damienen** [comment]
Solved. Closing.
