### ISSUE TITLE
Data NFT Marketplace: There has to be handling/messaging of concurrent actions failure while Data NFT is being procured.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#602]
Description:

Users have provided feedback of issue that arise from NFT being already Procured.

These include
1. 2 Users attempt to procure the same NFT. https://devnet-explorer.multiversx.com/transactions/f499b76b1690f8e0e5b345c40a64b0bfdb27e7bafe93bd0ea9a68073fbca7584
2. Updating price of an NFT while it is being procured throws error.
3. Delisting of an NFT while it is being procured throws error.

The users only is able to view useful information of the failure if they browse to the explorer instance of the transaction.

**Comment by BogdanCostinas** [comment]
Description:
Some community testers faced some issues with understanding the messages on the explorer after they received an error inside the Data DEX after performing actions like Delist/Update price. Some of the errors were due to the fact that the NFTs were already procured by others and there was not enough quantity to be updated. 

Suggestion:
Add a specific message AND/OR even a pop-up message when somebody procures your Data NFT

**Comment by fuzzyduke** [comment]
Updating price scenario

https://devnet-explorer.multiversx.com/transactions/a33d616155efa2ed57d25dc0863139b9980997b5595b9a121976c8bcb20a3c2b

**Comment by damienen** [comment]
The only way to do this is to manually check via API when the TX goes and match TXs between them for each transaction the user sends.

I feel like this is way too much overhead. Moreover, treating this case in this way is not implemented on any marketplace (probably exactly because of this problem)

I suggest we do not fix this. @newbreedofgeek what do you think?

**Comment by damienen** [comment]
We could capture the SC error message and provide some clues on why the TX failed

**Comment by icegriffinguru** [comment]
Initial version pushed.
Detect failure of "Purchase", "De-List", "Update Price" transactions and show a toast with error message from SC.
Only in marketplace.

**Comment by fuzzyduke** [comment]
Verified. Fixed. 3 scenarios verified; procure, update price, delisting

![image](https://user-images.githubusercontent.com/121969933/236744250-fa90412a-5445-44ac-895f-10dd5c662e15.png)

![image](https://user-images.githubusercontent.com/121969933/236743352-9326670b-a5c9-4efb-b9f7-19b824ff16a7.png)

![image](https://user-images.githubusercontent.com/121969933/236743740-80155261-8829-4643-888f-fee82564e969.png)
