### ISSUE TITLE
Allow profile accessing for any address

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#864]

**Comment by icegriffinguru** [comment]
Updated

**Comment by fuzzyduke** [comment]
While accessing a profile in non logged in mode blank screen is seen.

https://deploy-preview-882--frosty-hermann-85ca4f.netlify.app/profile/erd1ttexfnluaky2zcqr2xljgrth5580j6rx2fya2mx7mruamfvfxxjske3tea

![image](https://github.com/Itheum/data-dex/assets/121969933/5ccc626f-b366-4cac-b812-edd209ce1546)

**Comment by fuzzyduke** [comment]
While access another users profile, a high load time is encountered. If logged in user A is access user B profile the below screen is seen for more than 10 seconds.

![image](https://github.com/Itheum/data-dex/assets/121969933/ec84798d-60a6-4752-a693-c0a999619e46)

**Comment by damienen** [comment]
The loading time is irrelevant to this specific issue. We can get a better loading time after we have this done

**Comment by damienen** [comment]
Awaiting UX/UI design

**Comment by newbreedofgeek** [comment]
Assigning to @harbzy for a UI design idea.

Basically when you click on these links:
![Image](https://github.com/Itheum/data-dex/assets/743169/58d7a887-f007-497b-9894-af3a954360da)


- The "Profile" page needs to load like our "Data NFT Details page" as a model. 
- The Profile page should also work in "full screen mode". (Note: Our "Data NFT Details page" also work in this way. where it works as a model and also in stand alone mode"

**Comment by newbreedofgeek** [comment]
- hover animation on tile "view details Page as model"
- Use the "recent Data Card tiles" as guide but also should show : name / description / total supply / Royalties / Creation time

@icegriffinguru you can take this... get design from @Enciusan

**Comment by icegriffinguru** [comment]
https://www.figma.com/file/pc6aeAZYHyQ5rNMemaOxyd/DATA-DEX?node-id=1868%3A8840&mode=dev
Here you have Page 7 - Data Creator Profile page

**Comment by fuzzyduke** [comment]
Items implemented on #946.

1. Link to profile when clicking on "Profile" from the menu. Clicking on creator to view creator profile yet to be seen.
2. Profile page works in full screen mode.
3. Feilds shown; name / description / total supply / Royalties / Creation time

![image](https://github.com/Itheum/data-dex/assets/121969933/91707cbb-5531-4a7a-9642-01e9d988c951)

**Comment by fuzzyduke** [comment]
Issue 1

When on the profile page, if you click on creator or owner the page opens in the background i.e., the original page.

Steps
1. Click on details
https://deploy-preview-897--frosty-hermann-85ca4f.netlify.app/profile/erd17eg43r3xvenuc0yayauhqf066lum52phnytvw0tnvy677up7caese7gv3g
2. Click on creator or Owner on the popup modal.
3. It is observed that the main page updates behind the popup modal.

![Image](https://github.com/Itheum/data-dex/assets/121969933/88db8285-bbe5-4e9a-b857-1f7ad894113d)


Issue 2

1. When clicking on creator the redirection is seen to the "Created Data NFT(s)" tab which is fine
2. When clicking on Owner, the suggestion is to go to the "Listed Data NFT(s)" tab under the profile page. Reasoning is because Owners will not necessarily show created Data NFT(s) as owners will largely be purchasers.

**Comment by fuzzyduke** [comment]
Verified fixed.

1. Redirects correctly for both mobile and desktop.
2. Detail page redirects are correct. 
3. Offers show correctly.
4. Able to purchase from the detail page of the creator listings.
