### ISSUE TITLE
Add async DB updates for when a tx is sent from our FE

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#879]
We do not wait for TXs to be complete if we use nativeAuth for endpoint protection

**Comment by bucurdavid** [comment]
Currently, our cron job is scheduled to run at regular intervals (1 minute), which might coincide with user transactions just before the cron job execution. This can lead to the live update being overridden by the blockchain state because transaction is still pending, being successful after the cron finished the job.

**Solution** (if backend is available): 
- Depending on real-time updates applied to the backend API
- Scheduling the cron job during periods of reduced traffic on the data-dex

**Pending** (backend API):
- Implement a method to accurately retrieve the correct "last offer index", preventing potential conflicts when two users simultaneously add offers and ensuring that they do not overwrite each other's offer.

⚠ This feature must be tested rigorously.

**Comment by damienen** [comment]
See about the tokenLogin mainnet redirect

**Comment by damienen** [comment]
Just swap localStorage to sessionStorage

**Comment by bucurdavid** [comment]
Testing should occur after merging to milestone 1.4.0, as other developers working on their branches don't have the feature.

**Comment by newbreedofgeek** [comment]
Test on https://github.com/Itheum/data-dex/pull/907

@fuzzyduke

**Comment by bucurdavid** [comment]
Theoretically it is not related. I'll keep an eye on it

**Comment by fuzzyduke** [comment]
Verified. Closing.

Tests mainly involved monitoring Update Price, Purchasing, Listing, Delisting and monitoring state post transaction.
