### ISSUE TITLE
Data NFT activity shows additional activity not related to the connected data NFT.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#908]
There is activity seen on a Data NFT even prior to its mint. kindly find the below.

https://devnet-explorer.multiversx.com/nfts/DATANFTFT4-3ba099-01d5

![image](https://github.com/Itheum/data-dex/assets/121969933/ccfe7964-d293-4bcb-ab94-00774c7aadd6)

**Comment by bucurdavid** [comment]
This bug is happening due to some weird things happening on devnet (rollback). The table maps the entire transaction history and if some transactions are missing the accurate history cannot be build leading to this kind of bug.

When mainnet will start to grow this should be migrated into the backend service because it has some limitations on FE ( we can build history up to 10.000 txs)

**Comment by damienen** [comment]
Delete the extra entries from the database then close this off.

**Comment by damienen** [comment]
Nothing to do on our end, we can close this.
