### ISSUE TITLE
Various Grammar errors on this page

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#949]
Various grammar errors on this page:
https://deploy-preview-859--frosty-hermann-85ca4f.netlify.app/getwhitelisted

Needs a final review from Marketing and Product and then to fix issues and close off.

**Comment by fuzzyduke** [comment]
Text change requested in main block.

**Item 1**

Previous text
"Are you a Data Creator? Do you generate valuable data insights for the Blockchain, DeFi, Gaming, Entertainment, or any other industry? If so, we want to work with you!

Get Whitelisted to be part of the first batch of Data Creators to mint Data NFTs. Make history!"

New text
"It’s time to own and trade your data

Whether you’re a data creator, researcher, content creator, analyst, gamer, or a pioneering project - you have the power to redefine the value of your data. Transform your unique datasets into a new asset class by minting your very own Data NFTs.

Don’t just be a part of the change, lead it."

**Item 2**

Previous text
"Data enterprises gather and manage vast amounts of data, often of diverse types and from various sources. Now, with Data NFTs, they can further unlock the potential of their data assets."

New text
"Enterprises manage an array of diverse assets and data. The introduction of Data NFTs offers a groundbreaking way to both secure and monetize these resources, opening up a new era of opportunities."

**Item 3**
Please use MultiversX across the page instead of just Multiversx. (X in caps)

**Item 4**
"Explore Trending Data NFTs Collections" to
"Explore Trending Data NFT Collections"

**Comment by newbreedofgeek** [comment]
Title should change from:

"Fully Unlock your Data’s Value and Mint as an NFT" to "Fully Unlock your Data’s Value by Minting it as a Data NFT"

**Comment by fuzzyduke** [comment]
Verified, all text is updated.
